name: Dakara

on:
  schedule:
    - cron: '11,42 18,19 * * *'

  workflow_dispatch:

jobs:

  daka:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium httpx
      
      # - name: Random Delay
      #   run: python ./src/delay.py

      - name: Payload
        env: 
          MY_SECRET_USERNAME: ${{ secrets.MY_SECRET_USERNAME }}
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
          DAKA_RUNNER: GitHub
        run: python ./fork/daka.py
        